#!/usr/bin/env bash
set -e

if [ -z "$1" ]; then
  #echo "$(cat ~/src/config/tmux/README.md)"
  printf '%b\n' "$(cat ~/src/config/tmux/README.md)"
else
  if [ "$#" = 2 ]; then
    printf '%b\n' "$(cat ~/src/config/tmux/README.md|grep -A $2 -B $2 $1)"
  else
    printf '%b\n' "$(cat ~/src/config/tmux/README.md|grep $1)"
  fi
fi

